### ISSUE TITLE
Advantage over HyperPlanning's export

### ISSUE THREAD

**Issue by zdimension** [QuentinBeauchet/HyperplanningScrapEDT#1]
What's the advantage of using this scraper over HyperPlanning's export feature that generates an ICS file?

**Comment by QuentinBeauchet** [comment]
There is none, i made it because my school removed the option to download the .ics from their site. Of course i would have used an export feature instead of doing it myself if there was one.
![Capture d’écran du 2022-09-19 12-01-53](https://user-images.githubusercontent.com/74865653/190974409-9bfa85c4-8265-41fb-aa8c-f7cdce3220b5.png)

**Comment by zdimension** [comment]
You need to be logged in to have the .ical export file:
![image](https://user-images.githubusercontent.com/4533568/190975325-a06a57c3-01f0-4d49-9613-13580260ddde.png)

Here's your timetable http://sco.polytech.unice.fr/1/Telechargements/ical/Edt_BEAUCHET.ics?version=2022.0.3.1&idICal=5103BCC648A035744126B66559D68F5D&param=643d5b312e2e36325d2666683d3126663d31

This link can be imported into any calendar app, such as Google Calendar, and has the advantage of being automatically updated with HyperPlanning so in the event of classes being moved or cancelled you'll get the information immediately

Btw we're in the same class lmao I'm the one with the Paramount tee-shirt, left seats in the back

**Comment by QuentinBeauchet** [comment]
Thanks for the link but i think because i'm in the M2 Ingenierie and not from Polytech i can't connect to the site and have to access it as guest, we all tried with my mates and it's the same error.
![image](https://user-images.githubusercontent.com/74865653/190975953-58ecf498-cc8c-4013-92b0-6eee2ae3fa19.png)
